---
- name: Harden Red Hat system
  hosts: redhat
  become: yes
  tasks:
    - name: Ensure the latest updates are installed
      yum:
        name: '*'
        state: latest

    - name: Disable root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

    - name: Disable password authentication for SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH

    - name: Ensure firewalld is installed
      yum:
        name: firewalld
        state: present

    - name: Ensure firewalld is running and enabled
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Allow SSH through the firewall
      firewalld:
        service: ssh
        permanent: yes
        state: enabled
        immediate: yes

    - name: Ensure no unneeded services are running
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - telnet
        - rsh
        - rexec
        - ftp

    - name: Set secure permissions on sensitive files
      file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: '/etc/passwd', owner: 'root', group: 'root', mode: '0644' }
        - { path: '/etc/shadow', owner: 'root', group: 'root', mode: '0600' }
        - { path: '/etc/gshadow', owner: 'root', group: 'root', mode: '0600' }
        - { path: '/etc/group', owner: 'root', group: 'root', mode: '0644' }

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
