---
- name: Patch Red Hat system
  hosts: redhat
  become: yes
  tasks:
    - name: Update all packages to the latest version
      yum:
        name: '*'
        state: latest

    - name: Reboot the server if needed
      reboot:
        when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_version']|int == 8
